version: "3"
services:

  db:
    image: "postgres:11"
    network_mode: bridge
    environment:
      - POSTGRES_DB=feelingIndicator
      - POSTGRES_USER=feelingIndicator
      - POSTGRES_PASSWORD=feelingIndicator
    container_name: "feelingIndicator"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data2

  feelingtrackerapp:
    image: feeling-tracker-app:latest
    network_mode: bridge
    container_name: feelingtrackerapp
    expose:
      - 8080
      - 8000
    ports:
      - 8080:8080
      - 8000:8000
    depends_on:
      - db
    links:
      - db

volumes:
  my_dbdata: